/**
 * Decision core for the agent-team file-ownership hook.
 *
 * Kept free of I/O so the matcher can be tested directly — the escaping and
 * ordering rules below are where this logic goes wrong, and a broken matcher
 * decides ownership arbitrarily rather than failing loudly.
 */

import path from 'node:path'

/** Agent type -> globs that type may write. A leading `!` subtracts. */
export type OwnershipMap = Record<string, string[]>

export type Decision = { allow: true } | { allow: false; reason: string }

export interface DecideInput {
	/**
	 * Probed from real hook payloads: a teammate's carries `agent_type`, the
	 * lead's carries none. `session_id` is shared between them, so absence of
	 * the type is the only lead signal available.
	 */
	agentType: string | undefined
	filePath: string | undefined
	cwd: string | undefined
	map: OwnershipMap
}

const ALLOW: Decision = { allow: true }

/** Regex metacharacters that carry no glob meaning and must match literally. */
const REGEX_SPECIAL = /[.*+?^${}()|[\]\\]/g

/**
 * Compile a glob to an anchored RegExp.
 *
 * Single left-to-right scan rather than successive replacements. A
 * replacement-based version has to protect `**` from being rescanned by the
 * `*` rule, typically with sentinel characters — and if those sentinels are
 * lost or collide, the pattern silently degenerates into one that matches
 * everything or nothing. Scanning removes that failure mode by construction.
 *
 * `*` stays within a segment, `**` crosses them, `?` is one character.
 */
export function globToRegExp(glob: string): RegExp {
	let source = '^'

	for (let i = 0; i < glob.length; ) {
		const char = glob[i]

		if (char === '*') {
			if (glob[i + 1] === '*') {
				// `**/` also matches zero directories, so `**/*.ts` covers `a.ts`.
				if (glob[i + 2] === '/') {
					source += '(?:.*/)?'
					i += 3
					continue
				}
				source += '.*'
				i += 2
				continue
			}
			source += '[^/]*'
			i += 1
			continue
		}

		if (char === '?') {
			source += '[^/]'
			i += 1
			continue
		}

		source += char.replace(REGEX_SPECIAL, '\\$&')
		i += 1
	}

	return new RegExp(source + '$')
}

/**
 * Resolve `filePath` against `cwd` and express it relative to that root.
 *
 * Traversal is normalized before the inside/outside judgment, so `..` cannot
 * smuggle a path out of the project and back into an owned glob.
 */
export function relativize(filePath: string, cwd: string): { rel: string; outside: boolean } {
	const root = path.resolve(cwd)
	const rel = path.relative(root, path.resolve(root, filePath))
	const outside = rel === '' || rel === '..' || rel.startsWith(`..${path.sep}`) || path.isAbsolute(rel)

	return { rel: rel.split(path.sep).join('/'), outside }
}

/**
 * Every uncertain path returns `allow`. An unenforced write is recoverable; a
 * session that cannot write anything is not, and this runs on every edit.
 */
export function decide({ agentType, filePath, cwd, map }: DecideInput): Decision {
	if (!agentType) return ALLOW
	// `$`-prefixed keys are inline documentation in the shipped JSON map.
	if (agentType.startsWith('$')) return ALLOW
	if (!filePath) return ALLOW
	if (!cwd) return ALLOW
	if (!map || typeof map !== 'object') return ALLOW
	if (!Object.prototype.hasOwnProperty.call(map, agentType)) return ALLOW

	const entry = map[agentType]
	if (!Array.isArray(entry)) return ALLOW

	const globs = entry.filter((glob): glob is string => typeof glob === 'string')
	const owned = globs.filter((glob) => !glob.startsWith('!'))
	const excluded = globs.filter((glob) => glob.startsWith('!')).map((glob) => glob.slice(1))

	const { rel, outside } = relativize(filePath, cwd)

	if (outside) {
		return {
			allow: false,
			reason:
				`File ownership: ${filePath} is outside the project, and ${agentType} owns paths within the project only. ` +
				`If this write is genuinely needed, report it to the lead with SendMessage rather than working around it.`,
		}
	}

	const isOwned = owned.some((glob) => globToRegExp(glob).test(rel))
	const isExcluded = excluded.some((glob) => globToRegExp(glob).test(rel))

	if (isOwned && !isExcluded) return ALLOW

	return {
		allow: false,
		reason:
			`File ownership: ${agentType} does not own ${rel}. ` +
			`It owns: ${owned.length > 0 ? owned.join(', ') : '(nothing)'}. ` +
			`Do not edit this file, and do not reach it another way. ` +
			`If the change is needed — a missing export, an untestable private, or a real defect — ` +
			`report it to the lead with SendMessage and let the owner make it.`,
	}
}
